default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: Practise_development
  username: Idfy  

test:
  <<: *default
  database: Practise_test
  username: Idfy  
  password: user

production:
  <<: *default
  database: Practise_production
  