default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: practise__development
  username: idfy  
  password: user

test:
  <<: *default
  database: practise__test
  username: idfy  
  password: user

production:
  <<: *default
  database: Practise_production
  